#define TILESET_COUNT_X 49
#define TILESET_COUNT_Y 22

#define TILESET_STEP_X (1.0/TILESET_COUNT_X)
#define TILESET_STEP_Y (1.0/TILESET_COUNT_Y)

#define TILESET_BONES_TILE (v4(TILESET_STEP_X*0, TILESET_STEP_Y*6, TILESET_STEP_X, TILESET_STEP_Y))